"""Yale Bright Star Catalog (BSC5, V/50) を assets/stars/bsc5.csv へ変換する。

使い方:
    python tools/convert_bsc5.py path/to/bsc5.dat assets/stars/bsc5.csv

入力は http://tdc-www.harvard.edu/catalogs/bsc5.html の bsc5.dat（固定長テキスト）。
出力は 1 行 1 星の "ra_deg,dec_deg,vmag,bv"（J2000）。位置や等級を持たない項目は落とす。
"""
import sys


def convert(source: str, target: str) -> None:
    rows = []
    with open(source, encoding="latin-1") as file:
        for line in file:
            line = line.rstrip("\n")
            if len(line) < 114:
                continue
            ra_text, dec_text, mag_text, bv_text = line[75:83], line[83:90], line[102:107], line[109:114]
            if not ra_text.strip() or not mag_text.strip():
                continue
            hours, minutes, seconds = int(ra_text[0:2]), int(ra_text[2:4]), float(ra_text[4:8])
            ra = (hours + minutes / 60.0 + seconds / 3600.0) * 15.0
            sign = -1.0 if dec_text[0] == "-" else 1.0
            dec = sign * (int(dec_text[1:3]) + int(dec_text[3:5]) / 60.0 + int(dec_text[5:7]) / 3600.0)
            mag = float(mag_text)
            bv = float(bv_text) if bv_text.strip() else 0.0
            rows.append(f"{ra:.4f},{dec:.4f},{mag:.2f},{bv:.2f}")
    with open(target, "w", encoding="utf-8", newline="\n") as file:
        file.write("# Yale Bright Star Catalog, 5th revised edition (Hoffleit & Warren 1991), CDS V/50.\n")
        file.write("# Columns: right ascension (deg, J2000), declination (deg, J2000), V magnitude, B-V color index.\n")
        file.write("# Generated by tools/convert_bsc5.py.\n")
        file.write("\n".join(rows) + "\n")
    print(f"{len(rows)} stars written to {target}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
